[tool.poetry]
name = "soap-controller"
version = "0.1.0"
description = "Graphical User Interface to control a running Liquidsoap instance"
authors = ["Martin Kirchgessner <martin.kirch@gmail.com>"]
license = "GPL"
readme = "README.rst"
homepage = "https://github.com/martinkirch/soap-controller"
repository = "https://github.com/martinkirch/soap-controller"
keywords = ["radio", "liquidsoap", "gtk", "gui"]

[tool.poetry.dependencies]
python = "^3.7"
PyGObject = "^3.36.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
