[tool.poetry]
name = "soapbox"
version = "0.1.0"
description = "Companion scripts for a Liquidsoap radio"
authors = ["Martin Kirchgessner <martin.kirch@gmail.com>"]
license = "GPL"
readme = "README.rst"
homepage = "https://github.com/martinkirch/soapbox"
repository = "https://github.com/martinkirch/soapbox"
keywords = ["radio", "liquidsoap", "gtk", "gui"]

[tool.poetry.scripts]
soapbox_gui = "soapbox.gui:main"
soapbox_daemon = "soapbox.daemon:main"

[tool.poetry.dependencies]
python = "^3.7"
PyGObject = "^3.36.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
