[tool.poetry]
name = "showergel"
version = "0.1.0-alpha1"
description = "Companion application for a Liquidsoap radio"
authors = ["Martin Kirchgessner <martin.kirch@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.rst"
homepage = "https://github.com/martinkirch/showergel"
repository = "https://github.com/martinkirch/showergel.git"
keywords = ["radio", "liquidsoap"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Players"
]

[tool.poetry.scripts]
showergel = "showergel:main"
showergel_install = "showergel.install:main"

[tool.poetry.dependencies]
python = "^3.7"
PyGObject = "^3.36.1"
sqlalchemy = "^1.3.19"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
